export const TOPIC_COINS = [
  {
    id: 1,
    name: '美食控',
    content: 'AR空間社群',
    status: 0,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/=D8n-mE2JU-dRK=_1729568643.2',
  },
  {
    id: 2,
    name: '咖啡控',
    content: 'AR空間社群',
    status: 0,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/nOO9g=zcMmaHD2n_1729734365.2',
  },
  {
    id: 3,
    name: '飲料控',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/zZJsWEIv2sS8mI1_1717140288.2',
  },
  {
    id: 4,
    name: '寵物控',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/HkydnubPURre5bn_1717140403.2',
  },
  {
    id: 5,
    name: '時尚控',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/aH5Lz=7FmcdJTBV_1729582887.2',
  },
  {
    id: 6,
    name: '西堤牛排',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/public/assets/images/store/store2.jpg',
  },
  {
    id: 7,
    name: '御私藏',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/public/assets/images/store/store3.jpg',
  },
  {
    id: 8,
    name: '星巴克',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/public/assets/images/store/store4.jpg',
  },
  {
    id: 9,
    name: '台北威秀',
    content: 'AR空間社群',
    status: 1,
    image: 'https://i.meee.com.tw/vzSicbe.png',
  },
  {
    id: 10,
    name: '台中威秀',
    content: 'AR空間社群',
    status: 1,
    image: 'https://i.meee.com.tw/vzSicbe.png',
  },
  {
    id: 11,
    name: '高雄威秀',
    content: 'AR空間社群',
    status: 1,
    image: 'https://i.meee.com.tw/vzSicbe.png',
  },
  {
    id: 12,
    name: '美食控',
    content: 'AR空間社群',
    status: 0,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/=D8n-mE2JU-dRK=_1729568643.2',
  },
  {
    id: 13,
    name: '咖啡控',
    content: 'AR空間社群',
    status: 0,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/nOO9g=zcMmaHD2n_1729734365.2',
  },
  {
    id: 14,
    name: '飲料控',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/zZJsWEIv2sS8mI1_1717140288.2',
  },
  {
    id: 15,
    name: '寵物控',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/HkydnubPURre5bn_1717140403.2',
  },
  {
    id: 16,
    name: '時尚控',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/womo/p/store/aH5Lz=7FmcdJTBV_1729582887.2',
  },
  {
    id: 17,
    name: '西堤牛排',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/public/assets/images/store/store2.jpg',
  },
  {
    id: 18,
    name: '御私藏',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/public/assets/images/store/store3.jpg',
  },
  {
    id: 19,
    name: '星巴克',
    content: 'AR空間社群',
    status: 1,
    image: 'https://d1q14jmvwk39e0.cloudfront.net/public/assets/images/store/store4.jpg',
  },
  {
    id: 20,
    name: '台北威秀',
    content: 'AR空間社群',
    status: 1,
    image: 'https://i.meee.com.tw/vzSicbe.png',
  },
  {
    id: 21,
    name: '台中威秀',
    content: 'AR空間社群',
    status: 1,
    image: 'https://i.meee.com.tw/vzSicbe.png',
  },
  {
    id: 22,
    name: '高雄威秀',
    content: 'AR空間社群',
    status: 1,
    image: 'https://i.meee.com.tw/vzSicbe.png',
  },
];
